minimum_pre_commit_version: "3.5.0"
default_stages: [pre-commit]

repos:
  - repo: local
    hooks:
      - id: nox-fmt
        name: nox fmt
        entry: nox
        args: ["-s", "fmt"]
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: nox-lint
        name: nox lint
        entry: nox
        args: ["-s", "lint"]
        language: system
        pass_filenames: false
        stages: [pre-commit]
